channels:
  - plotly
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - abseil-cpp=20230802.0
  - aiofiles=22.1.0
  - aiosqlite=0.18.0
  - anyio=3.5.0
  - appnope=0.1.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow-cpp=11.0.0
  - asttokens=2.0.5
  - attrs=23.1.0
  - aws-c-common=0.6.8
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.11
  - aws-sdk-cpp=1.8.185
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bleach=4.1.0
  - boost-cpp=1.73.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.08.22
  - cairo=1.16.0
  - catalogue=2.0.7
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.0.4
  - colorama=0.4.6
  - comm=0.1.2
  - commonmark=0.9.1
  - confection=0.0.4
  - contourpy=1.0.5
  - cramjam=2.6.2
  - cryptography=41.0.3
  - cycler=0.11.0
  - cymem=2.0.6
  - cyrus-sasl=2.1.28
  - cython-blis=0.7.9
  - dataclasses=0.8
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.5.0
  - fastparquet=2023.8.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonttools=4.25.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - fsspec=2023.9.2
  - future=0.18.3
  - gdk-pixbuf=2.42.10
  - gettext=0.21.0
  - gflags=2.2.2
  - giflib=5.2.1
  - glib=2.69.1
  - glog=0.5.0
  - graphite2=1.3.14
  - graphviz=2.50.0
  - grpc-cpp=1.48.2
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - gtest=1.14.0
  - gts=0.7.6
  - harfbuzz=4.3.0
  - icu=68.1
  - idna=3.4
  - imbalanced-learn=0.11.0
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - importlib_resources=5.2.0
  - ipykernel=6.25.0
  - ipython=8.12.2
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.4
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter_client=7.4.9
  - jupyter_console=6.6.3
  - jupyter_core=5.3.0
  - jupyter_events=0.6.3
  - jupyter_server=1.23.4
  - jupyter_server_fileid=0.9.0
  - jupyter_server_ydoc=0.8.0
  - jupyter_ydoc=0.2.4
  - jupyterlab=3.6.3
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.22.0
  - jupyterlab_widgets=3.0.5
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - langcodes=3.3.0
  - lcms2=2.12
  - lerc=3.0
  - libboost=1.73.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcurl=8.4.0
  - libcxx=14.0.6
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgd=2.3.3
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libiconv=1.16
  - libllvm14=14.0.6
  - libnghttp2=1.57.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libpq=12.15
  - libprotobuf=3.20.3
  - librsvg=2.54.4
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libtool=2.4.6
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.10.4
  - libxslt=1.1.37
  - llvm-openmp=14.0.6
  - lxml=4.9.3
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - munkres=1.1.4
  - murmurhash=1.0.7
  - mysql=5.7.24
  - nbclassic=0.5.5
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nltk=3.8.1
  - notebook=6.5.4
  - notebook-shim=0.2.2
  - nspr=4.35
  - nss=3.89.1
  - numexpr=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openjpeg=2.3.0
  - openssl=3.0.12
  - orc=1.7.4
  - packaging=23.1
  - pandas=2.0.3
  - pandocfilters=1.5.0
  - pango=1.50.7
  - parso=0.8.3
  - pathy=0.10.2
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.0.1
  - pip=23.2.1
  - pixman=0.40.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.10.0
  - plotly=4.12.0
  - ply=3.11
  - pooch=1.7.0
  - poppler=22.12.0
  - poppler-data=0.4.11
  - preshed=3.0.6
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - prompt_toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=11.0.0
  - pycparser=2.21
  - pydantic=1.10.12
  - pygments=2.15.1
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.8.18
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-graphviz=0.20.1
  - python-json-logger=2.0.7
  - python-levenshtein=0.12.2
  - python-tzdata=2023.3
  - pytz=2023.3.post1
  - pyyaml=6.0
  - pyzmq=23.2.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtconsole=5.4.2
  - qtpy=2.2.0
  - qtwebkit=5.212
  - re2=2022.04.01
  - readline=8.2
  - regex=2023.10.3
  - requests=2.31.0
  - retrying=1.3.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=12.6.0
  - scikit-learn=1.3.0
  - scipy=1.10.1
  - seaborn=0.12.2
  - send2trash=1.8.0
  - setuptools=68.0.0
  - shellingham=1.5.3
  - sip=6.6.2
  - six=1.16.0
  - smart_open=5.2.1
  - snappy=1.1.9
  - sniffio=1.2.0
  - soupsieve=2.5
  - spacy=3.5.3
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.5
  - sqlite=3.41.2
  - srsly=2.4.6
  - stack_data=0.2.0
  - terminado=0.17.1
  - thinc=8.1.10
  - threadpoolctl=2.2.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.3.3
  - tqdm=4.65.0
  - traitlets=5.7.1
  - typer=0.7.0
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - urllib3=1.26.16
  - utf8proc=2.6.1
  - wasabi=0.10.1
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.41.2
  - widgetsnbextension=4.0.5
  - xz=5.4.2
  - y-py=0.5.9
  - yaml=0.2.5
  - ypy-websocket=0.8.2
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - cloudpickle==3.0.0
      - en-core-web-lg==3.5.0
      - en-core-web-md==3.5.0
      - en-core-web-sm==3.5.0
      - imageio==2.32.0
      - lazy-loader==0.3
      - lime==0.2.0.1
      - llvmlite==0.41.1
      - networkx==3.1
      - numba==0.58.1
      - pywavelets==1.4.1
      - scikit-image==0.21.0
      - shap==0.43.0
      - slicer==0.0.7
      - tifffile==2023.7.10
